#!/usr/bin/env python3
"""splendid_baralytics/capabilities.py — API surface for the monorepo."""
from __future__ import annotations
import os, sys
from typing import Dict, List
_base = os.environ.get("PC_BASE_DIR", "/sessions/clever-charming-euler/mnt/GitHub/scavengers_guild/ai_processes")
sys.path.insert(0, os.path.abspath(_base))
from capabilities_core import run  # noqa: E402

LOCAL_CAPABILITIES: List[Dict] = [
    {"id": "sdfz_parse", "name": "Parse .sdfz demo",
     "description": "TypeScript library — parse a SpringRTS .sdfz demo to structured JSON.",
     "usage": "node dist/index.js <demo.sdfz>", "tags": ["parser", "demo"]},
    {"id": "npm_test", "name": "Run demo-parser tests", "description": "Jest suite.",
     "usage": "npm test", "tags": ["test", "npm"]},
    {"id": "npm_build", "name": "Build the parser", "description": "tsc build to dist/.",
     "usage": "npm run build", "tags": ["build", "npm"]},
    {"id": "gex_pc", "name": "gex_research pc registry",
     "description": "10-cap pc registry for BAR replay metrics (bar_run_metric, bar_headless_extract, bar_demo_roster, bar_split, bar_self_reclaim, bar_catalog, bar_view_report, bar_new_run, bar_add_metric, bar_add_situation).",
     "usage": "cd gex_research/ai_processes && python capabilities.py --spec --pretty",
     "tags": ["gex", "pc", "metrics"]},
    {"id": "bar_calc", "name": "bar-calc CLI",
     "description": "Walk-time / breakeven / TROI / wind math for BAR.",
     "usage": "python bar-calc/bar_distance.py --help", "tags": ["bar-calc"]},
    {"id": "barbots_parse_intent", "name": "barbots parse-intent",
     "description": "Intent .md -> goal DAG JSON.",
     "usage": "node barbots/planner/parse-intent.mjs <intents/x.md>",
     "tags": ["barbots", "planner"]},
    {"id": "barbots_expand_goals", "name": "barbots expand-goals",
     "description": "Goal DAG -> flat costed action list.",
     "usage": "node barbots/planner/expand-goals.mjs <intents/x.md>",
     "tags": ["barbots", "planner"]},
    {"id": "barbots_project", "name": "barbots project.mjs",
     "description": "Action list -> per-goal projected timeline via eco_engine.",
     "usage": "node barbots/planner/project.mjs <intents/x.md>",
     "tags": ["barbots", "planner"]},
    {"id": "barbots_fusion_sweep", "name": "Legion T2 fusion sweep",
     "description": "Sweep medmex count 0-4 with own-battery optimization; sourced legion_unitdefs.json.",
     "usage": "node barbots/planner/experiments/legion-t2-fusion-path.mjs",
     "tags": ["barbots", "experiment", "fusion"]},
    {"id": "barbots_next_steps", "name": "barbots next-steps (compound)",
     "description": "Given a state ref (--position/--demo/--state) + intent, project next N actions after time T. Primary bot query.",
     "usage": "node barbots/planner/next-steps.mjs (--position <n> | --demo <p> [--t <sec>]) --intent-name <name> [--n 5] [--from-t 0] [--summary]",
     "tags": ["barbots", "planner", "compound", "next-steps", "live"]},
    {"id": "barbots_extract_position_demo", "name": "barbots extract-position (demo)",
     "description": "Headless BAR .sdfz parse at time T -> eco_engine createState() with Legion residual calibration.",
     "usage": "node barbots/planner/extract-position.mjs --demo <path.sdfz> --t <sec> [--player <name>] [--out <file>]",
     "tags": ["barbots", "state", "demo", "sdfz", "extract"]},
    {"id": "barbots_extract_position_file", "name": "barbots extract-position (file)",
     "description": "Load positions/named/<name>.json into eco_engine createState() params.",
     "usage": "node barbots/planner/extract-position.mjs --position <name>",
     "tags": ["barbots", "state", "position", "extract"]},
    {"id": "barbots_list_intents", "name": "barbots list intents",
     "description": "Enumerate barbots/intents/*.md - the declared build orders.",
     "usage": "node barbots/planner/next-steps.mjs --list-intents",
     "tags": ["barbots", "intents", "discovery"]},
    {"id": "barbots_live_reader", "name": "barbots LiveReader",
     "description": "Fog-honest live-state reader polling bar_analytic_server /api/state; emits econ/builderIdle/builderBusy/gameReset/gameEnd/error.",
     "usage": "import { LiveReader } from './barbots/reader/live-reader.mjs'",
     "tags": ["barbots", "reader", "live", "fog-honest"]},
    {"id": "barbots_adapter_replan", "name": "barbots adapter (planned)",
     "description": "PLANNED: merge projected timeline with LiveReader events, trigger re-projection on divergence.",
     "usage": "(not yet implemented)",
     "tags": ["barbots", "adapter", "planned"]},
    {"id": "barbots_executor", "name": "barbots executor (planned)",
     "description": "PLANNED: issue in-game commands via Lua Spring.GiveOrderToUnit.",
     "usage": "(not yet implemented)",
     "tags": ["barbots", "executor", "planned"]},
    {"id": "barbots_demo_roster", "name": "barbots demo roster + start positions",
     "description": "Read a .sdfz header, emit per-allyTeam roster (name/team/faction/skill/rank/startPos + startBox). Winning team starred.",
     "usage": "node barbots/planner/demo-roster.mjs <path.sdfz> [--summary]",
     "tags": ["barbots", "demo", "sdfz", "roster", "start-position"]},
    {"id": "barbots_find_demo", "name": "barbots find demo",
     "description": "Scan BAR demo directory and return newest demo(s) matching --players / --min-duration / --match regex.",
     "usage": "node barbots/planner/find-demo.mjs [--dir <path>] [--players N] [--min-duration <sec>] [--match <regex>] [--n 1] [--json]",
     "tags": ["barbots", "demo", "find", "selector", "sdfz"]},
    {"id": "opening_builds_reports", "name": "Opening builds reports",
     "description": "Pre-generated replay opening analyses (OPENING_BUILDS_YYYY-MM-DD_*.md).",
     "usage": "ls OPENING_BUILDS_*.md", "tags": ["report"]},
]
if __name__ == "__main__":
    run(LOCAL_CAPABILITIES, root_dir=__file__)
